angular.module("themeConfig", [])
.constant("data", "_nor")
.constant("ApiKey", " https://micrositeifd.azurewebsites.net/api/v1/bc75536a-5c79-4c8d-adfa-cd9dacda59bb")
.constant("parentLink", "https://www.norwegian.com/")
.constant("secondaryLink", "https://www.norwegian.com/")
.constant("languageID", "154")
.constant("languageCode", "en")
.constant("movieCat", "1252")
.constant("movieNewRelease", "1253")
.constant("movieAllFilter", "1273")
.constant("tvCat", "1255")
.constant("tvAll", "1274")
.constant("audioCat", "925")
.constant("audioAll", "941");
